# Generated by Django 4.2.30 on 2026-07-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='accent_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='resume',
            name='custom_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_family',
            field=models.CharField(default='Inter', max_length=50),
        ),
    ]
